### ISSUE TITLE
pin connection in readme is ambiguous

### ISSUE THREAD

**Issue by vertexi** [GrgoMariani/Raspberry-Pico-Pocket-Gamer#1]
```
 ILI9341         Pico (RP2040)
 
SDI     <-----> PIN 7
 DC     <-----> PIN 18
```

Is that looks right?

**Comment by GrgoMariani** [comment]
I am not  sure which pins are ambiguous here? Are they the ILI9341 pins or the Pico pins?

Or I should have used a table view instead of the  `<--->`

**Comment by vertexi** [comment]
``` 
ILI9341         Pico (RP2040)
 
 T_IRQ  <-----> PIN 20
 T_DO   <-----> PIN 8
 T_DIN  <-----> PIN 11
 T_CS   <-----> PIN 21
 T_CLK  <-----> PIN 10
 SDO    <-----> PIN 4
 LED    <-----> PIN 26 (or directly to 3v3)
 SCK    <-----> PIN 6
 SDI    <-----> PIN 7
 DC     <-----> PIN 18
 RESET  <-----> PIN 17
 CS     <-----> PIN 16
 GND    <-----> GND
 VCC    <-----> 3V3
```

In your readme.md `DC` is connected to `PIN 7` and no `SDI` connection. Is `DC` connected to `PIN 18` and additional `SDI` connected to `PIN 7` actually?

https://github.com/GrgoMariani/Raspberry-Pico-Pocket-Gamer/blob/cee9d1816ce6a5cd8139d0b70835c48106036510/src/interface/ili9341.c#L10-L11

**Comment by GrgoMariani** [comment]
Wow, I totally missed this somehow. Thanks

Fixed here:
https://github.com/GrgoMariani/Raspberry-Pico-Pocket-Gamer/commit/1d05ba25afbb2bcb7ee6206863f30f153ec64852
