### ISSUE TITLE
iteration variable inside the GPU_DrawFilledSquare function related to width should be uint16_t type.

### ISSUE THREAD

**Issue by vertexi** [GrgoMariani/Raspberry-Pico-Pocket-Gamer#2]
https://github.com/GrgoMariani/Raspberry-Pico-Pocket-Gamer/blob/64e7681111eb4cdafd256c5934835caad37d7567/src/gpu.c#L138

**Comment by GrgoMariani** [comment]
Fixed with commit bd800916ee5d35518b4f443422bdb1f45e4a924f

I expected the width and height to always be under 256 somehow.
